# Generated by Django 3.2.14 on 2022-08-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axiom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_buffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.TextField()),
                ('container', models.TextField()),
                ('unload_time', models.TextField()),
                ('workers', models.TextField()),
                ('w1', models.TextField()),
                ('w2', models.TextField()),
                ('w3', models.TextField()),
                ('w4', models.TextField()),
                ('w5', models.TextField()),
            ],
        ),
    ]
