# Generated by Django 3.2.14 on 2022-08-02 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axiom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_work',
            field=models.TextField(default=''),
        ),
    ]
